# Generated by Django 3.0.7 on 2020-09-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='菜单名')),
                ('url', models.CharField(max_length=60, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Menu', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='班组')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('mobile_phone', models.CharField(max_length=32, unique=True, verbose_name='手机号')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role', verbose_name='角色')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Team', verbose_name='班组')),
            ],
        ),
    ]
