# Generated by Django 3.0.7 on 2020-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '班组表', 'verbose_name_plural': '班组表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='menu',
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(to='account.Menu', verbose_name='权限'),
        ),
    ]
