# Generated by Django 3.0.7 on 2020-09-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200916_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menu',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
    ]
