# Generated by Django 3.0.7 on 2020-09-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20200917_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40, verbose_name='维修项目')),
            ],
            options={
                'verbose_name': '维修项目表',
                'verbose_name_plural': '维修项目表',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_num', models.CharField(max_length=20, verbose_name='车牌号码')),
                ('wip', models.CharField(db_index=True, max_length=20, verbose_name='工单号码')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='登记日期')),
                ('register_time', models.TimeField(auto_now_add=True, verbose_name='登记时间')),
                ('estimate_finish_date', models.DateField(auto_now_add=True, verbose_name='预计完成日期')),
                ('estimate_finish_time', models.TimeField(auto_now_add=True, verbose_name='预计完成时间')),
                ('actual_finish_date', models.DateField(auto_now=True, verbose_name='实际完成日期')),
                ('actual_finish_time', models.TimeField(auto_now=True, verbose_name='实际完成时间')),
                ('accident_work_order', models.CharField(max_length=10, verbose_name='事故维修工单')),
                ('moto_work_order', models.CharField(max_length=10, verbose_name='摩托维修工单')),
                ('oil_service', models.CharField(max_length=10, verbose_name='机油保养')),
                ('over_registration', models.CharField(max_length=10, verbose_name='重复进场工单')),
                ('service_status', models.CharField(db_index=True, default='派工维修', max_length=32, verbose_name='维修状态')),
                ('quick_service_team', models.ForeignKey(blank=True, db_column='快修班组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_service', to='account.Team', verbose_name='快修班组')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile', verbose_name='服务顾问')),
                ('service_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.ServiceProject', verbose_name='维修项目')),
                ('service_team', models.ForeignKey(blank=True, db_column='机电班组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_team', to='account.Team', verbose_name='机电班组')),
            ],
            options={
                'verbose_name': '车辆信息表',
                'verbose_name_plural': '车辆信息表',
            },
        ),
    ]
